### PR TITLE
Update translated_sentences.txt

### PR DESCRIPTION
**Pull request by suguhara**
fix

### CODE REVIEW

**Comment by suguhara** [comment]
https://reversed.tistory.com/attachment/cfile2.uf@2202D63552C1E5BD1F92E2.npa this file make the game textbox goes horizontial. Just copy it into the game folder

**Comment by klesun** [comment]
Wow, it sure does!
image

**Comment by klesun** [comment]
Let me know if you need assistance with translation files. I'm currently [incorporating](https://github.com/klesun/muramasa-vn-translation/blob/master/public/assets/mb_hero_route/rec2/adminKeyframes.json) Garejei translations in addition to the google translate, but it may not seem obvious how they are mapped to each other.

(I also have a dream to [OCR out](https://cloud.google.com/vision/docs/drag-and-drop) Maa-chan's translations from the videos on day...)

**Comment by longendoh2411** [comment]
> Wow, it sure does!
> image

How do u do that. I also copyed it to the game file but still not working

**Comment by longendoh2411** [comment]
> Wow, it sure does!
> image

**Comment by suguhara** [comment]
> > Wow, it sure does!
> > image
> 
> How do u do that. I also copyed it to the game file but still not working

you need to start new game

**Comment by longendoh2411** [comment]
> > > Wow, it sure does!
> > > image
> > 
> > 
> > How do u do that. I also copyed it to the game file but still not working
> 
> you need to start new game

C2B87706-4852-468F-9B99-6B36AEEE6EB9

**Comment by longendoh2411** [comment]
> > > Wow, it sure does!
> > > image
> > 
> > 
> > How do u do that. I also copyed it to the game file but still not working
> 
> you need to start new game

Which file did you put it ??

**Comment by suguhara** [comment]
> > > Wow, it sure does!
> > > image
> > 
> > 
> > How do u do that. I also copyed it to the game file but still not working
> 
> you need to start new game

why don't you install the game first? Run setup to install the game. And then put the patch there.
image

**Comment by longendoh2411** [comment]
> > > > Wow, it sure does!
> > > > image
> > > 
> > > 
> > > How do u do that. I also copyed it to the game file but still not working
> > 
> > 
> > you need to start new game
> 
> why don't you install the game first? Run setup to install the game. And then put the patch there.
> image

I make it. Tks

**Comment by suguhara** [comment]
Muramasa's offical translation is coming

**Comment by klesun** [comment]
@suguhara you mean from Nitroplus? Could you, please, share a link to the info if you have one?

**Comment by suguhara** [comment]
> @suguhara you mean from Nitroplus? Could you, please, share a link to the info if you have one? We are fan-translating the Tyrant route atm, it could get awkward 😰
https://twitter.com/jastusa/status/1415840757886328832 and https://vndb.org/r81304 It's Jast doing it

**Comment by suguhara** [comment]
It will be released on 24/08

**Pull request merged**
