### PR TITLE
Correct machine tranlsation artifacts in Revenge Route rec1: Kagemei -> Kageaki

### PR DESCRIPTION
**Pull request by klesun**
Hi. I was watching the walkthrough and noticed these few mistakes in the translation. Would love to see these correction accepted ;)

### CODE REVIEW

**Comment by klesun** [comment]
Hi, thanks for the contribution, will push this update to youtube soon.

**Comment by suguhara** [comment]
I know how to make a patch and I'm using Maa-chan's translation for it but is his translation that good?

**Comment by suguhara** [comment]
https://drive.google.com/file/d/1X1BsqVrfRYCwjkhhp5VW6ptj3_AQhfRp/view?usp=sharing here the script after I extract

**Comment by klesun** [comment]
Hi. Maa-chan's translation is pretty good imo. He has some small mistakes from time to time and intentional mistranslation of swear words, but it's much better than google translate.

Thanks for the link, looks useful.

**Comment by klesun** [comment]
@suguhara fyi, I started working on a text recognition software to automatically extract Maa-chan's text from videos:
https://github.com/klesun/detect-still-frames/blob/main/README.md

**Comment by suguhara** [comment]
> @suguhara fyi, I started working on a text recognition software to automatically extract Maa-chan's text from videos:
> https://github.com/klesun/detect-still-frames

I am working on making patch using maa-chan translation
161582130_1947389145408161_4830094584689522778_n

**Comment by suguhara** [comment]
I have to say that the patch is very hard to make. It's need 2 byte words to work and some scripts are crashing or skipping. What a pain.

**Comment by klesun** [comment]
Kanbaru, senpai!

**Comment by klesun** [comment]
Btw, I found out that the scripts you sent me were [CP932](https://fix-encoding.com/), even though some tools incorrectly recognized them as JIS, which has some shared characters, but did not match all the nss files fully (resulted in question marks on some characters).

**Comment by suguhara** [comment]
Yeah, that's why i'm using font to replace, and i'm using the korean patch since they make the textbox bigger, the horizontial patch I sent you just isn't big enough

**Comment by suguhara** [comment]
https://user-images.githubusercontent.com/81801486/114697112-b29ffb80-9d47-11eb-8af2-3af0d0170799.mp4

**Comment by suguhara** [comment]
I encountered the H-scene what should I do?

**Comment by klesun** [comment]
Maa-chan did not translate them afaik. I have google translations, if it helps:
https://github.com/klesun/muramasa-vn-translation/blob/master/public/assets/ma_common_route/ma01_crimson_craft/translated_sentences.txt

https://lbry.tv/@muramasa-vn-translation-nsfw:c?view=about

**Comment by klesun** [comment]
Hey, bro. Fyi, I started re-translating using [DeepL](https://www.deepl.com/en/translator), it seems to be of a higher quality than Google Translate:
https://github.com/klesun/muramasa-vn-translation/blob/master/public/assets/mc_revenge_route/rec2/translated_sentences_deepl_web.txt

Though it has to be postprocessed by a script to remove Neural Networks translation artifacts:
https://github.com/klesun/muramasa-vn-translation/blob/bb0b6498e712f0dbb34a2f1cedd438b9bfdeb77c/backend/assets_index.js#L46

**Comment by suguhara** [comment]
my gosh I got tired from doing this so I drop it

**Comment by klesun** [comment]
That's sad ;c
Would you consider to share the tools you used? Maybe I could continue your work.

**Comment by suguhara** [comment]
https://drive.google.com/file/d/1dBYBA3Rji2AoSGAtrH7Ue-4ecjbCVQz8/view here what I've done so far. You would like to use full width letter in the patch so that the game won't have any issue

**Comment by suguhara** [comment]
you could use garbro or nipa to unpack and repack

**Comment by klesun** [comment]
Ok, thanks, I will try my best!
I will be posting my progress in this repo, feel free to drop by to chat if you feel like it. Could even give you contributor permissions.

**Comment by suguhara** [comment]
yeah sure

**Comment by klesun** [comment]
Yo, I did not understand from your comment on youtube whether you are working on that again or not, but just in case, wanted to share something interesting I found:
`ma04_014.nss`
```
<PRE @box0>
[text2160]
//◆テキスト横書き表示
　
　　　　<PRE>The paradox of "Tell and apple".</PRE>

</PRE>
```
Seems like `<PRE>` tag can be used to display non-full width latin characters. Could be useful probably...

**Comment by suguhara** [comment]
No, I am not

**Comment by suguhara** [comment]
hype

**Comment by suguhara** [comment]
I just want to tell you that I've completed applying chapter 1 translation except H-scene.

**Comment by suguhara** [comment]
image
image

**Comment by suguhara** [comment]
Do you think the yellow poem need retranslating? 'Cause maa-chan's translation looks similar to gg translate.

**Comment by klesun** [comment]
```
《奇跡を行う聖人は衆生を救い神を呪って嘔吐する》
《黄金の兜の覇王は万里を征し愛馬と共に川底へ沈む》
《湖の美姫は国を捨て愛を選び糞尿に溺れて刑死する》
《孤赤児は蚯蚓の血を母の乳とし三夜して腹より腐る》
《生命よこの賛歌を聞け笑い疲れた怨嗟を重ねて》
《生命よこの祈りを聞け怒りおののく喜びを枕に》
《百年の生は炎と剣の連環が幾重にも飾り立てよう》
《七日の生は闇と静寂に守られ無垢に光り輝くだろう》
《獣よ踊れ野を馳せよ唄い騒いで猛り駆けめぐれ》
《いまや如何なる鎖も檻も汝の前には朽ちた土塊》
```
maachan:
https://youtu.be/AXSc9oNXSTk?t=1735
gg translate:
```
<< The saint who performs miracles saves sentient beings and curses God and vomits >>
《The Overlord of the Golden Helmet conquers Mari and sinks to the bottom of the river with his beloved horse》
《Lake beauty abandons the country, chooses her love and is drowned in her manure and is sentenced to death》
《The lonely baby uses the blood of the worm as her mother's milk and rots from his belly for three nights》
《Listen to this hymn of life, laugh and pile up tired grudges》
《Listen to this prayer, life, with anger and joy as a pillow》
《Let's decorate the life of 100 years with multiple layers of flames and swords》
《The life of the 7th will be protected by darkness and silence and will shine innocently》
《Beast, dance in the field, sing and run wildly》
《Now any chains or cages have decayed in front of you》
```
I think Maachan would be offended by your statement...

**Comment by suguhara** [comment]
Wait could you upload the H-scene in chapter 1 with deepl

**Comment by suguhara** [comment]
urgh I plan to release the patch for first chapter and prologue

**Comment by suguhara** [comment]
ma01_022vs.nss is freaking lag since it has lots of effect, it takes time to display text but I made it possible somehow . Btw, I have finished editing chapter 1.

**Comment by suguhara** [comment]
https://vndb.org/r79675 done

**Comment by suguhara** [comment]
why does your friend still on translating for muramasa? The english version is out

**Comment by klesun** [comment]
Wow, it [sure is](https://www.youtube.com/watch?v=42w4RZv1U6c).

**Pull request merged**
